const data = {
  response_code: 0,
  results: [
    {
      category: 'Entertainment: Film',
      type: 'multiple',
      difficulty: 'easy',
      question: "What breed of dog was 'Marley' in the film 'Marley & Me'?",
      correct_answer: 'Labrador Retriever',
      incorrect_answers: ['Golden Retriever', 'Dalmatian', 'Shiba Inu'],
    },
    {
      category: 'Entertainment: Film',
      type: 'multiple',
      difficulty: 'hard',
      question: "Which was the first of Alfred Hitchcock's movies to be filmed in colour?",
      correct_answer: 'Rope',
      incorrect_answers: ['Psycho', 'Vertigo', 'Rebecca'],
    },
    {
      category: 'Science: Mathematics',
      type: 'multiple',
      difficulty: 'medium',
      question: 'How many zeros are there in a googol?',
      correct_answer: '100',
      incorrect_answers: ['10', '1,000', '1,000,000'],
    },
    {
      category: 'Vehicles',
      type: 'multiple',
      difficulty: 'medium',
      question:
        'What part of an automobile engine uses lobes to open and close intake and exhaust valves, and allows an air/fuel mixture into the engine?',
      correct_answer: 'Camshaft',
      incorrect_answers: ['Piston', 'Drive shaft', 'Crankshaft'],
    },
    {
      category: 'History',
      type: 'boolean',
      difficulty: 'medium',
      question: 'The first televised presidential debate was between Jimmy Carter and Gerald Ford.',
      correct_answer: 'False',
      incorrect_answers: ['True'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'easy',
      question: 'What was the name of the cancelled sequel of Team Fortress?',
      correct_answer: 'Team Fortress 2: Brotherhood of Arms',
      incorrect_answers: [
        'Team Fortress 2: Desert Mercenaries',
        'Team Fortress 2: Operation Gear Grinder',
        'Team Fortress 2: Return to Classic',
      ],
    },
    {
      category: 'Animals',
      type: 'multiple',
      difficulty: 'medium',
      question: 'Cashmere is the wool from which kind of animal?',
      correct_answer: 'Goat',
      incorrect_answers: ['Sheep', 'Camel', 'Llama'],
    },
    {
      category: 'History',
      type: 'multiple',
      difficulty: 'medium',
      question: 'When did Jamaica recieve its independence from England? ',
      correct_answer: '1962',
      incorrect_answers: ['1492', '1963', '1987'],
    },
    {
      category: 'Science: Computers',
      type: 'multiple',
      difficulty: 'easy',
      question: 'What does the Prt Sc button do?',
      correct_answer: "Captures what's on the screen and copies it to your clipboard",
      incorrect_answers: [
        'Nothing',
        "Saves a .png file of what's on the screen in your screenshots folder in photos",
        'Closes all windows',
      ],
    },
    {
      category: 'Vehicles',
      type: 'boolean',
      difficulty: 'medium',
      question: "The Japanese Shinkansen beat the French TGV's speed record for fastest electric rail train.",
      correct_answer: 'False',
      incorrect_answers: ['True'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'easy',
      question: 'Pokémon Go is a location-based augmented reality game developed and published by which company?',
      correct_answer: 'Niantic',
      incorrect_answers: ['Rovio', 'Zynga', 'Supercell'],
    },
    {
      category: 'General Knowledge',
      type: 'multiple',
      difficulty: 'easy',
      question: "What type of animal was Harambe, who was shot after a child fell into it's enclosure at the Cincinnati Zoo?",
      correct_answer: 'Gorilla',
      incorrect_answers: ['Tiger', 'Panda', 'Crocodile'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'easy',
      question: 'What ingredient is NOT used to craft a cake in Minecraft?',
      correct_answer: 'Bread',
      incorrect_answers: ['Wheat', 'Milk', 'Egg'],
    },

    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'easy',
      question: 'Which of these is NOT a playable character in the 2016 video game Overwatch?',
      correct_answer: 'Invoker',
      incorrect_answers: ['Mercy', 'Winston', 'Zenyatta'],
    },
    {
      category: 'Science & Nature',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What is the atomic number of the element Strontium?',
      correct_answer: '38',
      incorrect_answers: ['73', '47', '11'],
    },
    {
      category: 'Animals',
      type: 'multiple',
      difficulty: 'hard',
      question: 'What is the scientific name of the cheetah?',
      correct_answer: 'Acinonyx jubatus',
      incorrect_answers: ['Panthera onca', 'Lynx rufus', 'Felis catus'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What was the FIRST Valve game to have VR?',
      correct_answer: 'The Lab',
      incorrect_answers: ['Dota 2', 'Destinations', 'Half-Life 2'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'medium',
      question: 'In the Portal series, Aperture Science was founded under what name in the early 1940s?',
      correct_answer: 'Aperture Fixtures',
      incorrect_answers: ['Aperture Lavatories', 'Aperture Science Innovators', 'Wheatley Laboratories'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'easy',
      question: 'In what city in the dystopia alternate future of Half-Life 2 do you first start in?',
      correct_answer: 'City 17',
      incorrect_answers: ['City 18', 'City 6', 'City 45'],
    },
    {
      category: 'History',
      type: 'multiple',
      difficulty: 'hard',
      question: 'The Second Boer War in 1899 was fought where?',
      correct_answer: 'South Africa',
      incorrect_answers: ['Argentina', 'Nepal', 'Bulgaria'],
    },
    {
      category: 'Entertainment: Music',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What is the relationship between the band members of American rock band King of Leon?',
      correct_answer: 'Brothers & cousins',
      incorrect_answers: ['Childhood friends', 'Former classmates', 'Fraternity house members'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'hard',
      question: "What's the name of the halloween-related Sims 4 Stuff Pack released September 29th, 2015?",
      correct_answer: 'Spooky Stuff',
      incorrect_answers: ["Ghosts n' Ghouls", 'Nerving Nights', 'Fearful Frights'],
    },
    {
      category: 'Vehicles',
      type: 'boolean',
      difficulty: 'medium',
      question: 'Arriva is owned by the Deutsche Bahn.',
      correct_answer: 'True',
      incorrect_answers: ['False'],
    },
    {
      category: 'Science: Gadgets',
      type: 'multiple',
      difficulty: 'medium',
      question: 'Who patented a steam engine that produced continuous rotary motion?',
      correct_answer: 'James Watt',
      incorrect_answers: ['Nikola Tesla', 'Albert Einstein', 'Alessandro Volta'],
    },
    {
      category: 'Science: Computers',
      type: 'multiple',
      difficulty: 'hard',
      question: 'Which of the following is the oldest of these computers by release date?',
      correct_answer: 'TRS-80',
      incorrect_answers: ['Commodore 64', 'ZX Spectrum', 'Apple 3'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What element does the Zinogre use in Monster Hunter?',
      correct_answer: 'Thunder',
      incorrect_answers: ['Ice', 'Fire', 'Water'],
    },
    {
      category: 'General Knowledge',
      type: 'multiple',
      difficulty: 'medium',
      question: 'When was Hubba Bubba first introduced?',
      correct_answer: '1979',
      incorrect_answers: ['1984', '1972', '1980'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'medium',
      question: 'Who is the main character in most of the games of the YS series?',
      correct_answer: 'Adol Christin ',
      incorrect_answers: ["Character doesn't have a name", 'Estelle Bright', 'Roger Wilco'],
    },
    {
      category: 'Vehicles',
      type: 'multiple',
      difficulty: 'easy',
      question: 'The LS1 engine is how many cubic inches?',
      correct_answer: '346',
      incorrect_answers: ['350', '355', '360'],
    },
    {
      category: 'Entertainment: Television',
      type: 'boolean',
      difficulty: 'medium',
      question: 'Klingons respect their disabled comrades, and those who are old, injuried, and helpless.',
      correct_answer: 'False',
      incorrect_answers: ['True'],
    },
    {
      category: 'Science: Computers',
      type: 'multiple',
      difficulty: 'hard',
      question: 'What vulnerability ranked #1 on the OWASP Top 10 in 2013?',
      correct_answer: 'Injection ',
      incorrect_answers: ['Broken Authentication', 'Cross-Site Scripting', 'Insecure Direct Object References'],
    },
    {
      category: 'Entertainment: Comics',
      type: 'multiple',
      difficulty: 'easy',
      question: 'The main six year old protagonist in Calvin and Hobbes is named after what theologian?',
      correct_answer: 'John Calvin',
      incorrect_answers: ['Calvin Klein', 'Calvin Coolidge', 'Phillip Calvin McGraw'],
    },
    {
      category: 'Entertainment: Film',
      type: 'multiple',
      difficulty: 'easy',
      question: 'Where does the original Friday The 13th movie take place?',
      correct_answer: 'Camp Crystal Lake',
      incorrect_answers: ['Packanack', 'Higgins Haven', 'Camp Forest Green'],
    },
  ],
};

export default data;
